#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.
server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_rest
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/migration/db.changelog-master.xml

  springdoc:
    api-docs:
      enabled: false
    swagger-ui:
      enabled: true
      url: /api-external/openapi.yaml
      validator-url: none

logging:
  level:
    org.springframework.security: DEBUG
