server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_rest
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/migration/db.changelog-master.xml
    drop-first: false

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure: DEBUG

encryption:
  secret-key: my-super-secret-key-for-encryption-service

jwt:
  access-private-key-path: classpath:keys/private.pem
  access-public-key-path: classpath:keys/public.pem